### ISSUE TITLE
Determine a state management strategy for frontend react app

### ISSUE THREAD

**Issue by Yasirunet** [Yasirunet/OpenIntra#4]
There are lot of ways out there for managing state in React. But we think most of those are overwhelming and lot of things to do. The most popular one in the industry right now is [**Redux**](https://redux.js.org/). There lot of competitors also available such as **MobX**.

According to my opinion, with the introduction of [React hooks](https://reactjs.org/docs/hooks-intro.html) the state management of react is become lot easier and it solved lot of hassles in state management.

## Global State
Passing prop from the parent component to the child until the data get the component that needs the data can be messy with the growth of the application. (Aka **prop-drilling**) Also, the mutate the state can be even harder.  
To avoid this error most of the state management libraries such as Redux, MobX use *global state* to avoid issue mentioned above.

## what we actually need?
Most of the time in SPA we need to fetch data from our backend and cache those to further use. As well as share the state between components. According to my opinion to do these things, the Redux or similar solutions are overwhelming. 
Instead, I'm suggesting the following solution(s) for state management here.
- Use the library called React Query to fetch data from our backend. (As well as caching, re-fetching)
- User React hooks and Context API for share state between components.

### What actually [React Query](https://github.com/tannerlinsley/react-query) offers?
According to their documentation, the following are the features they offer. 
> Transport/protocol/backend agnostic data fetching (REST, GraphQL, promises, whatever!)
> Auto Caching + Refetching (stale-while-revalidate, Window Refocus, Polling/Realtime)
> Parallel + Dependent Queries
> Mutations + Reactive Query Refetching
> Multi-layer Cache + Automatic Garbage Collection
> Paginated + Cursor-based Queries
> Load-More + Infinite Scroll Queries w/ Scroll Recovery
> Request Cancellation
> React Suspense + Fetch-As-You-Render Query Prefetching
> Dedicated Devtools (React Query Devtools)

**Comment by bihanviranga** [comment]
Very good writeup, Yasiru. :partying_face: 
I have used redux before, and I agree that redux would be too overwhelming.
I just went through react-query documentation and it looks suitable for the job. Looks similar to context API but it automates many things apparently.

My vote is on react-query.

**Comment by SamadhiWathsala** [comment]
The most impressive explanation yasiru..👌
whether the Redux is most common state management library, I think it's enough for us to use the react-query.But if we use the Redux we can be helpful for reduce the performance issue because Redux is best performance rather than the react-query. However I haven't any experience with Redux before and it's easy to working with react-query for me😉 so **my votes for react-query**.✌😎

**Comment by Yasirunet** [comment]
Thank you very much for your insightful thoughts guys... Then let's move with React query and if at some point we need a more structured, more global state management solution let's add Redux as well. As I know there is no restriction to use Redux with react query. It just simplified the process of data fetching and caching with less boilerplate code.
