### ISSUE TITLE
Authentication endpoints

### ISSUE THREAD

**Issue by bihanviranga** [Yasirunet/OpenIntra#6]
If we can finalize the authentication endpoints from backend we can push it.

For example:
`POST api/login`
or
`POST api/user/login`

Any thoughts?

**Comment by Yasirunet** [comment]
Sounds great! I prefer to go with the second one.

**Comment by bihanviranga** [comment]
Awesome. If @SamadhiWathsala and @LakshikaDias has no objections, I'll push this.

**Comment by SamadhiWathsala** [comment]
@bihanviranga no issue. second one is fine

**Comment by LakshikaDias** [comment]
yep, second one is ok. No issue.

**Comment by bihanviranga** [comment]
Thanks guys. This is now closed via lakshikadias/openintra-backend#1
